### ISSUE TITLE
Incompatible with latest imglib2 versions

### ISSUE THREAD

**Issue by ctrueden** [saalfeldlab/imglib2-label-multisets#19]
Compilation with ImgLib2 v5.11.1:
```
$ mvn -Dimglib2.version=5.11.1 clean test
...
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[16,8] net.imglib2.type.label.LabelMultisetType is not abstract and does not override abstract method pow(net.imglib2.type.label.LabelMultisetType) in net.imglib2.type.operators.Pow
```

Compilation with ImgLib2 v5.12.0:
```
$ mvn -Dimglib2.version=5.12.0 clean test
...
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[16,8] net.imglib2.type.label.LabelMultisetType is not abstract and does not override abstract method pow(net.imglib2.type.label.LabelMultisetType) in net.imglib2.type.operators.Pow
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[58,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[60,40] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[67,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[157,21] cannot assign a value to final variable i
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[183,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[189,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[200,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[206,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[216,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[231,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[240,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[247,34] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[498,44] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[503,40] incompatible types: net.imglib2.type.Index cannot be converted to int
[ERROR] .../imglib2-label-multisets/src/main/java/net/imglib2/type/label/VolatileLabelMultisetType.java:[9,8] net.imglib2.type.label.VolatileLabelMultisetType is not abstract and does not override abstract method index() in net.imglib2.type.NativeType
```

Compilation with ImgLib2 v5.6.3, then running tests with 5.11.1 works. But running tests with 5.12.0 does not work:
```
$ mvn clean compile; mvn -Dimglib2.version=5.12.0 test                 
...
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.048 s <<< FAILURE! - in net.imglib2.type.label.LabelMultisetTypeTest
[ERROR] testInitializationMultipleEntries(net.imglib2.type.label.LabelMultisetTypeTest)  Time elapsed: 0.017 s  <<< ERROR!
java.lang.NoSuchFieldError: i
	at net.imglib2.type.label.LabelMultisetTypeTest.testInitializationMultipleEntries(LabelMultisetTypeTest.java:39)

[ERROR] testInitializationEmpty(net.imglib2.type.label.LabelMultisetTypeTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoSuchFieldError: i
	at net.imglib2.type.label.LabelMultisetTypeTest.testInitializationEmpty(LabelMultisetTypeTest.java:19)

[ERROR] testInitializationSingleEntry(net.imglib2.type.label.LabelMultisetTypeTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoSuchFieldError: i
	at net.imglib2.type.label.LabelMultisetTypeTest.testInitializationSingleEntry(LabelMultisetTypeTest.java:26)

[ERROR] testArgMax(net.imglib2.type.label.LabelMultisetTypeTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.NoSuchFieldError: i
	at net.imglib2.type.label.LabelMultisetTypeTest.testArgMax(LabelMultisetTypeTest.java:61)
```

@axtimwalde @tpietzsch This component needs update to imglib2 5.12.0, no?

**Comment by tpietzsch** [comment]
@ctrueden thanks for pointing it out!
@axtimwalde Do you want me to take care of it?

**Comment by bogovicj** [comment]
Had a look at this along with @cmhulbert looks like we get different behavior, or we're misunderstanding.

Specifically, from the current master, we see errors when using `imglib2-5.11.1`, but no problems with `imglib2-5.12.0` (see below).  And the last release,  (imglib2-label-multisets 0.10.0), [depended on `imglib2-5.12.0`](https://github.com/saalfeldlab/imglib2-label-multisets/blob/d0e22c4917b61aef8aed5245691ce1ba8d818125/pom.xml#L97).

This is all to say we're willing to help, but can't reproduce at the moment.

## imglib2 5.12.0
```
$ mvn -Dimglib2.version=5.12.0 clean test
...
[INFO] Results:
[INFO] 
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

```

## imglib2 5.11.1
```
$ mvn -Dimglib2.version=5.11.1 clean test
...
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/VolatileLabelMultisetType.java:[5,24] cannot find symbol
[ERROR]   symbol:   class Index
[ERROR]   location: package net.imglib2.type
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/VolatileLabelMultisetType.java:[58,16] cannot find symbol
[ERROR]   symbol:   class Index
[ERROR]   location: class net.imglib2.type.label.VolatileLabelMultisetType
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[58,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[60,41] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[67,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[157,34] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[157,23] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[183,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[189,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[200,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[206,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[216,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[231,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[240,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[247,35] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[498,45] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/LabelMultisetType.java:[503,41] int cannot be dereferenced
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/VolatileLabelMultisetType.java:[57,9] method does not override or implement a method from a supertype
[ERROR] /home/john/dev/imglib2/imglib2-label-multisets/src/main/java/net/imglib2/type/label/VolatileLabelMultisetType.java:[60,25] cannot find symbol
[ERROR]   symbol:   method index()

```

**Comment by ctrueden** [comment]
@bogovicj Thank you for investigating. I also cannot reproduce with 0.10.0 nor the master branch. It may be that I was testing against 0.9.0 rather than 0.10.0, since 0.9.0 is what pom-scijava currently references. So I'm closing this as a false alarm—apologies.
